bitwarden/helm-charts

.github/workflows/release.yml
This PR updates the `release` workflow to use our bot account and sign commits.
=> Update release workflow to use bot account

.github/workflows/linter.yml
This PR updates the `helm/chart-testing-action` to the latest version.
=> Linter workflow - Update chart-testing-action

.github/workflows/update-versions.yml
This PR adds the missing `-i` flag for updating the `helpers.tpl` file in-place.
=> Add -i flag to sed for updating in-place

.github/workflows/release.yml, .github/workflows/update-versions.yml, .github/workflows/version-bump.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
=> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

.github/workflows/update-versions.yml
This PR adds logic to update the `appVersion` value in the `Chart.yaml` file to match our latest Core version release.
=> Update Versions workflow - Add update to appVersion in Chart.yaml

charts/self-host/README.md, charts/self-host/templates/admin.yaml, charts/self-host/templates/api.yaml, charts/self-host/templates/attachments.yaml, charts/self-host/templates/events.yaml, charts/self-host/templates/helpers.tpl, charts/self-host/templates/icons.yaml, charts/self-host/templates/identity.yaml, charts/self-host/templates/notifications.yaml, charts/self-host/templates/post-install-db-migrator-job.yaml, charts/self-host/templates/pre-install-db-migrator-job.yaml, charts/self-host/templates/scim.yaml, charts/self-host/templates/sso.yaml, charts/self-host/templates/web.yaml, charts/self-host/values.yaml
Fixing tag overrides.
Updating Application Gateway README steps.
Increasing resources for API and Identity pods.
=> Updates ready for v0.1.8-Beta

charts/self-host/README.md, charts/self-host/ci/test-values.yaml, charts/self-host/values.yaml, examples/README.md
This fixes SSO and other path related issues by changing the Ingress path regexes.
=> Fix for SSO

charts/self-host/README.md, charts/self-host/templates/admin.yaml, charts/self-host/templates/api.yaml, charts/self-host/templates/events.yaml, charts/self-host/templates/icons.yaml, charts/self-host/templates/identity.yaml, charts/self-host/templates/notifications.yaml, charts/self-host/templates/post-install-db-migrator-job.yaml, charts/self-host/templates/scim.yaml, charts/self-host/templates/sso.yaml, charts/self-host/values.yaml
Updates around ingress documentation with changes for SSO.
=> Ingress updates

charts/self-host/templates/pre-install-hook-configmap.yaml, charts/self-host/values.schema.json, charts/self-host/values.yaml
=> Enabling family sync

charts/self-host/templates/admin.yaml, charts/self-host/templates/api.yaml, charts/self-host/templates/events.yaml, charts/self-host/templates/icons.yaml, charts/self-host/templates/identity.yaml, charts/self-host/templates/notifications.yaml, charts/self-host/templates/post-delete-hook.yaml, charts/self-host/templates/post-install-db-migrator-job.yaml, charts/self-host/templates/pre-install-db-migrator-job.yaml, charts/self-host/templates/pre-install-job.yaml, charts/self-host/templates/pre-install-secret-sql.yaml, charts/self-host/templates/scim.yaml, charts/self-host/templates/sso.yaml, charts/self-host/values.yaml
Adding the ability to use private registries for some of the support containers
=> Adding the ability to use private registries for some of the support containers

.github/workflows/build.yml
Reverts bitwarden/helm-charts#90
=> Revert "chore(deps): update actions/upload-artifact action to v4"

charts/self-host/ci/test-values.yaml, charts/self-host/templates/admin.yaml, charts/self-host/templates/api.yaml, charts/self-host/templates/attachments.yaml, charts/self-host/templates/events.yaml, charts/self-host/templates/icons.yaml, charts/self-host/templates/identity.yaml, charts/self-host/templates/mssql.yaml, charts/self-host/templates/notifications.yaml, charts/self-host/templates/post-install-db-migrator-job.yaml, charts/self-host/templates/pre-install-db-migrator-job.yaml, charts/self-host/templates/pre-install-job.yaml, charts/self-host/templates/pre-install-secret-keys.yaml, charts/self-host/templates/pre-install-secret-sql.yaml, charts/self-host/templates/scim.yaml, charts/self-host/templates/sso.yaml, charts/self-host/templates/volumes.yaml, charts/self-host/templates/web.yaml, charts/self-host/values.schema.json, charts/self-host/values.yaml
This PR adds the ability to use existing PVCs instead of creating new ones. It also has other miscellaneous changes. This is based off the community contribution [here](https://github.com/bitwarden/helm-charts/pull/98).
=> [DEVOPS-1713]  - Allow use of existing PVCs

charts/sm-operator/README.md
Adding beta release disclaimer to README.
=> Adding beta release disclaimer to README

.github/workflows/tests.yml, charts/sm-operator/ci/test-values.yaml
Removing imagePullSecrets from sm-operator tests
=> Removing imagePullSecrets from sm-operator tests

.github/workflows/build.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/update-versions-self-host.yml, .github/workflows/update-versions-sm-operator.yml, .github/workflows/version-bump-self-host.yml, .github/workflows/version-bump-sm-operator.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-372)
=> [BRE-372] - Clean up document start

.github/workflows/build-self-host.yml, .github/workflows/build-sm-operator.yml
Tracking:
[BRE-131](https://bitwarden.atlassian.net/browse/BRE-131)
Objective:
Updated the individual workflows to pass the secrets to the reusable workflow
[BRE-131]: https://bitwarden.atlassian.net/browse/BRE-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BRE-131] Passing secrets to reusable workflow

.github/workflows/build-self-host.yml, .github/workflows/build-sm-operator.yml
Fix for `bwwl` pre deployment
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for …
=> [BRE-494] - bwwl Pre Deployment fix

.github/workflows/tests.yml
- [BRE-655](https://bitwarden.atlassian.net/browse/BRE-655?atlOrigin=eyJpIjoiYjAyYTY0NGViMmRjNDU4Yjk4NjRjMDA5MDU0MmFjYjMiLCJwIjoiaiJ9)
This PR updates the `Tests` workflow so that it checks for proper success conditions. The `title` of the web vault was changed from `Bitwarden Web Vault` to `Bitwarden Web vault` [six months ago](https://github.com/bitwarden/clients/pull/10286) and that has been the cause of the errors.
- The `-i` flag was added to the `grep` command to be case insensitive.
- Using bash parameter expansion, the variable `bodyCheck` is converted to all lowercase before checking the condition.
- Protected functional changes …
=> BRE-655 - Update Tests workflow

.github/workflows/update-versions-self-host.yml
- Update verify version to point to GHCR
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) …
=> Update verify version to point to GHCR

.github/CODEOWNERS
[BRE-457](https://bitwarden.atlassian.net/browse/BRE-457)
Update CODEOWNERS according to the following points on the [Self-Host Ownership Plan](https://bitwarden.atlassian.net/wiki/spaces/BRE/pages/1333362690/Self-host+ownership+and+2025+Q1+plan#Self-host-ownership)
- BRE should own [the self-host helm chart](https://bitwarden.atlassian.net/wiki/spaces/BRE/pages/1333362690/Self-host+ownership+and+2025+Q1+plan#Self-host-helm-chart).
- Updated any …
=> [BRE-457] Updating CODEOWNERS for self-host ownership

charts/self-host/values.yaml
Bumps the MSSQL container image to the one we use to deploy Self Host. 
https://github.com/bitwarden/server/pull/3904
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …
=> Update MSSQL container image

.github/workflows/tests-target.yml, .github/workflows/tests.yml
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) …
=> Update permissions for CI PR Target workflow

.github/workflows/tests.yml
Checkout the correct ref when used with PR target or just by commit.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
=> Add ref logic to checkout the right ref for tests.yml

charts/self-host/Chart.yaml, charts/sm-operator/Chart.yaml
Fixes CI linting from change https://github.com/bitwarden/helm-charts/pull/275, turns out `ct` has been checking against https://github.com/dept-devops this entire time.
- 🤔 (`:thinking:`) or 💭 …
=> Set Bitwarden as the maintainer

.github/workflows/update-versions-self-host.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Fixing permissions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …
=> [BRE-831] Fixing permissions

.github/renovate.json
Fixes the formatting of the renovate file.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) …
=> Renovate: Fixed formatting

charts/self-host/ci/test-values.yaml, charts/self-host/values.yaml
https://bitwarden.atlassian.net/browse/BRE-1139
Switches to `alpine/openssl` for certificate generation.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …
=> Switch certGen values to alpine/openssl

.github/workflows/kubectl-image.yml
https://bitwarden.atlassian.net/browse/BRE-1189
Add a workflow that builds kubectl image and publishes it to ghcr.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …
=> BRE-1189: Add a workflow to build and publish kubectl image

charts/self-host/ci/test-values.yaml, charts/self-host/values.yaml
Update the kubectl image to point to the https://github.com/bitwarden/helm-charts/pkgs/container/helm-charts%2Fkubectl image.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
=> BRE-1136: [Self-Host] Update kubectl image to ghcr.io/bitwarden/helm-charts/kubectl

.github/workflows/_build.yml, .github/workflows/kubectl-image.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/update-versions-self-host.yml, .github/workflows/update-versions-sm-operator.yml, .github/workflows/version-bump-self-host.yml, .github/workflows/version-bump-sm-operator.yml
https://bitwarden.atlassian.net/browse/VULN-285
Perform cleanup of existing workflows to be in compliance with Zizmor and bwwl.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …
=> Clean up workflow files from Zizmor output
